version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
    - 8081:8081
    depends_on:
      - mongodb
  mongodb:
    platform: linux/x86_64
    image: "mongo"
    restart: always
    ports:
    - 27018:27017
